auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: production
  session:
    secret: superSecretSecret 
  providers:
    oidc:
      production:
        metadataUrl: "${KEYCLOAK_METADATA_URL}"
        clientId: "${KEYCLOAK_CLIENT_ID}"
        clientSecret: "${KEYCLOAK_CLIENT_SECRET}"
        prompt: auto
        callbackUrl: "$RHDH_BASE_URL/api/auth/oidc/handler/frame"
signInPage: oidc
catalog:
  import:
    entityFilename: catalog-info.yaml
    # pullRequestBranchName: rhdh-integration
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [API, Component, User, Group, Location, Resource, System, Template]
  locations:
    - type: url
      target: https://github.com/redhat-developer/rhdh/blob/main/catalog-entities/all.yaml
    - type: url
      target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml
    - type: url
      target: https://github.com/backstage/community-plugins/blob/main/workspaces/scaffolder-backend-module-kubernetes/plugins/kubernetes-actions/examples/templates/01-kubernetes-template.yaml
    - type: url
      target: https://github.com/janus-qe/acr-catalog/blob/main/catalog-info.yaml
    - type: url
      target: https://github.com/janus-qe/rhdh-test/blob/main/user.yml
      rules:
        - allow: [User]
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
      rules:
        - allow: [User, Group]
  providers:
    keycloakOrg:
      default:
        baseUrl: "${KEYCLOAK_BASE_URL}"
        loginRealm: "${KEYCLOAK_LOGIN_REALM}"
        realm: "${KEYCLOAK_REALM}"
        clientId: "${KEYCLOAK_CLIENT_ID}"
        clientSecret: "${KEYCLOAK_CLIENT_SECRET}"
        schedule:
          frequency: { minutes: 5 }
          initialDelay: { seconds: 15 }
          timeout: { minutes: 5 }