global:
  dynamic:
    # -- Array of YAML files listing dynamic plugins to include with those listed in the `plugins` field.
    # Relative paths are resolved from the working directory of the initContainer that will install the plugins (`/opt/app-root/src`).
    includes:
      # -- List of dynamic plugins included inside the `rhdh-community/rhdh` container image, some of which are disabled by default.
      # This file ONLY works with the `rhdh-community/rhdh` container image.
      - 'dynamic-plugins.default.yaml'

    # -- List of dynamic plugins, possibly overriding the plugins listed in `includes` files.
    # Every item defines the plugin `package` as a [NPM package spec](https://docs.npmjs.com/cli/v10/using-npm/package-spec),
    # an optional `pluginConfig` with plugin-specific backstage configuration, and an optional `disabled` flag to disable/enable a plugin
    # listed in `includes` files. It also includes an `integrity` field that is used to verify the plugin package [integrity](https://w3c.github.io/webappsec-subresource-integrity/#integrity-metadata-description).
    plugins:
    - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
      disabled: false
      pluginConfig:
        catalog:
          providers:
            keycloakOrg:
              default:
                baseUrl: "${KEYCLOAK_BASE_URL}"
                loginRealm: "${KEYCLOAK_LOGIN_REALM}"
                realm: "${KEYCLOAK_REALM}"
                clientId: "${KEYCLOAK_CLIENT_ID}"
                clientSecret: "${KEYCLOAK_CLIENT_SECRET}"
                schedule:
                  frequency:
                    minutes: 60
                  initialDelay:
                    seconds: 15
                  timeout:
                    minutes: 50
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
    extraEnvVarsSecrets:
      - rhdh-secrets